enum AnnouncementCategory {
  NEWS
  EVENT
  EMERGENCY
  ROAD_CLOSURE
  POWER_INTERRUPTION
  HEALTH_ADVISORY
  GENERAL_NOTICE
}

enum AnnouncementSortField {
  PUBLISHED_AT
  CREATED_AT
  TITLE
}

input AnnouncementSortInput {
  field: AnnouncementSortField! = CREATED_AT
  direction: SortDirection! = DESC
}

type Announcement implements Node {
  id: ID!
  cursor: Cursor!
  title: String!
  content: String!
  category: AnnouncementCategory!
  coverImageUrl: String
  isPinned: Boolean
  isPublished: Boolean
  publishedAt: DateTime
  createdBy: ID!
  updatedBy: ID
  deletedAt: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AnnouncementEdge implements Edge {
  cursor: Cursor!
  node: Announcement!
}

type AnnouncementConnection implements Connection {
  totalCount: Int!
  edges: [AnnouncementEdge!]!
  pageInfo: CursorPageInfo!
}

input AnnouncementCategoryFilterInput {
  equal: AnnouncementCategory
  in: [AnnouncementCategory!]
  notIn: [AnnouncementCategory!]
  notEqual: AnnouncementCategory
}

input AdminAnnouncementBooleanFilterInput {
  equal: Boolean
  in: [Boolean!]
  notIn: [Boolean!]
  notEqual: Boolean
}

input AnnouncementsFilterInput {
  category: AnnouncementCategoryFilterInput
}

input AdminAnnouncementsFilterInput {
  id: IDFilterInput
  category: AnnouncementCategoryFilterInput
  isPublished: AdminAnnouncementBooleanFilterInput
  isPinned: AdminAnnouncementBooleanFilterInput
  deletedAt: DateTimeFilterInput
  publishedAt: DateTimeFilterInput
}

input CreateAnnouncementInput {
  title: String!
  content: String!
  category: AnnouncementCategory!
  coverImageUrl: String
  isPinned: Boolean = false
  isPublished: Boolean = false
}

input UpdateAnnouncementInput {
  title: String!
  content: String!
  category: AnnouncementCategory!
  coverImageUrl: String
  isPinned: Boolean
  isPublished: Boolean
}

extend type Query {
  announcements(
    filter: AnnouncementsFilterInput
    sort: AnnouncementSortInput
    first: Int
    after: Cursor
  ): AnnouncementConnection!
  announcement(id: ID!): Announcement
  adminAnnouncements(
    filter: AdminAnnouncementsFilterInput
    sort: AnnouncementSortInput
    first: Int
    after: Cursor
  ): AnnouncementConnection!
  searchByAdminAnnouncements(
    search: String!
    first: Int
    after: Cursor
  ): [Announcement!]
}

extend type Mutation {
  createAnnouncement(input: CreateAnnouncementInput!): Announcement!
  updateAnnouncement(id: ID!, input: UpdateAnnouncementInput!): Announcement!
  deleteAnnouncement(id: ID!): Boolean!
  publishAnnouncement(id: ID!, isPublished: Boolean!): Announcement!
  pinAnnouncement(id: ID!, isPinned: Boolean!): Announcement!
}
