enum UserRole {
  USER
  ADMIN
  SUPER_ADMIN
}

enum ResetCodeStatus {
  VALID
  INVALID
  EXPIRED
}

type User implements Node {
  id: ID!
  email: String!
  role: UserRole!
  organizationId: String
  isActive: Boolean!
  firstName: String
  lastName: String
  position: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

type AuthPayload {
  accessToken: String!
  refreshToken: String!
  tokenType: String!
  expiresIn: Int!
  user: User!
}

type PasswordResetRequestResult {
  accepted: Boolean!
  message: String!
}

type PasswordResetCodeResult {
  status: ResetCodeStatus!
}

input LoginInput {
  email: String!
  password: String!
  organizationSlug: String
}

input RegisterUserInput {
  organizationSlug: String!
  email: String!
  password: String!
  confirmPassword: String!
  firstName: String
  lastName: String
}

input UpdateMyProfileInput {
  firstName: String
  lastName: String
  position: String
}

input ResetPasswordInput {
  email: String!
  code: String!
  newPassword: String!
}

extend type Query {
  me: User!
}

extend type Mutation {
  registerUser(input: RegisterUserInput!): AuthPayload!
  updateMyProfile(input: UpdateMyProfileInput!): User!
  login(input: LoginInput!): AuthPayload!
  logout: Boolean!
  requestPasswordReset(email: String!): PasswordResetRequestResult!
  verifyResetCode(email: String!, code: String!): PasswordResetCodeResult!
  resetPassword(input: ResetPasswordInput!): Boolean!
}
