enum PushPlatform {
  ANDROID
  IOS
  WEB
}

input PushDeviceMetadataInput {
  appOwnership: String
  appVersion: String
  buildVersion: String
  deviceName: String
  locale: String
  osName: String
  osVersion: String
}

input RegisterPushTokenInput {
  token: String!
  platform: PushPlatform!
  deviceMetadata: PushDeviceMetadataInput
}

input UnregisterPushTokenInput {
  token: String!
  platform: PushPlatform!
}

extend type Mutation {
  registerPushToken(input: RegisterPushTokenInput!): Boolean!
  unregisterPushToken(input: UnregisterPushTokenInput!): Boolean!
}
