enum StorePlatform {
  APPLE
  GOOGLE
}

type StorePurchaseResult {
  productId: String!
  status: String!
}

input VerifyStorePurchaseInput {
  store: StorePlatform!
  productId: String!
  transactionId: String
  purchaseToken: String!
}

extend type Mutation {
  verifyStorePurchase(input: VerifyStorePurchaseInput!): StorePurchaseResult!
}
