export const TOKENS = {
  ACCOUNT_DELETION_REQUESTS_REPOSITORY: 'ACCOUNT_DELETION_REQUESTS_REPOSITORY',
  ORGANIZATION_REPOSITORY: 'ORGANIZATION_REPOSITORY',
  NOTIFICATIONS_REPOSITORY: 'NOTIFICATIONS_REPOSITORY',
  PUSH_TOKENS_REPOSITORY: 'PUSH_TOKENS_REPOSITORY',
  SESSIONS_REPOSITORY: 'SESSIONS_REPOSITORY',
  SCHEDULER_LOCKS_REPOSITORY: 'SCHEDULER_LOCKS_REPOSITORY',
  STORE_ENTITLEMENTS: 'STORE_ENTITLEMENTS',
  STORE_PRODUCT_CATALOG: 'STORE_PRODUCT_CATALOG',
  STORE_PURCHASES_REPOSITORY: 'STORE_PURCHASES_REPOSITORY',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
};
