export const TOKENS = {
  ACCOUNT_DELETION_REQUESTS_REPOSITORY: 'ACCOUNT_DELETION_REQUESTS_REPOSITORY',
  ANNOUNCEMENTS_REPOSITORY: 'ANNOUNCEMENTS_REPOSITORY',
  ORGANIZATION_REPOSITORY: 'ORGANIZATION_REPOSITORY',
  NOTIFICATIONS_REPOSITORY: 'NOTIFICATIONS_REPOSITORY',
  PUSH_TOKENS_REPOSITORY: 'PUSH_TOKENS_REPOSITORY',
  MEMBERS_REPOSITORY: 'MEMBERS_REPOSITORY',
  SESSIONS_REPOSITORY: 'SESSIONS_REPOSITORY',
  SCHEDULER_LOCKS_REPOSITORY: 'SCHEDULER_LOCKS_REPOSITORY',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  WAITLIST_REPOSITORY: 'WAITLIST_REPOSITORY',
};
