import {
  CopyObjectCommand,
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import {
  getUploadExtensionForContentType,
  validateCreatePresignedUploadUrlBody,
} from './s3.validation';

export interface S3ConfigSummary {
  bucket: string;
  publicBaseUrl: string | null;
  region: string;
}

export interface StoredObjectInfo {
  contentLength: number;
  contentType: string | null;
}

/**
 * Project media lives under this server-owned prefix. Keys are generated by
 * the owning service, never taken from a caller.
 */
const PRIVATE_KEY_PATTERN =
  /^projects\/[a-f0-9]{24}\/(?:(?:assets|audio)\/[a-f0-9]{24}\.[a-z0-9]{2,5}|voice\/[a-f0-9]{24}\/[a-f0-9]{24}\.mp3|exports\/[a-f0-9]{24}\.(?:mp4|jpg)|ai-clips\/(?:[a-f0-9]{24}-frame-[0-8]\.jpg|[a-f0-9]{24}\.mp4))$/;

function assertPrivateKey(key: string): void {
  if (!PRIVATE_KEY_PATTERN.test(key)) {
    throw new BadRequestException('Invalid storage key.');
  }
}

export interface PresignedUploadUrlResponse {
  expiresInSeconds: number;
  key: string;
  publicUrl: string | null;
  uploadUrl: string;
}

@Injectable()
export class S3Service {
  private readonly bucket: string;
  private readonly client: S3Client;
  private readonly publicBaseUrl: string | null;

  constructor(private readonly configService: ConfigService) {
    const region = this.configService.get<string>('AWS_REGION');
    const accessKeyId = this.configService.get<string>('AWS_ACCESS_KEY_ID');
    const secretAccessKey = this.configService.get<string>(
      'AWS_SECRET_ACCESS_KEY',
    );
    const bucket = this.configService.get<string>('AWS_S3_BUCKET');

    if (!region || !accessKeyId || !secretAccessKey || !bucket) {
      throw new Error('AWS S3 configuration is incomplete.');
    }

    this.bucket = bucket;
    this.publicBaseUrl =
      this.configService.get<string>('AWS_S3_PUBLIC_BASE_URL') ?? null;
    this.client = new S3Client({
      region,
      credentials: {
        accessKeyId,
        secretAccessKey,
      },
    });
  }

  getConfigSummary(): S3ConfigSummary {
    return {
      region: this.configService.get<string>('AWS_REGION') ?? '',
      bucket: this.bucket,
      publicBaseUrl: this.publicBaseUrl,
    };
  }

  async createPresignedUploadUrl(
    uploadPathPrefix: string,
    contentType: string,
    expiresInSeconds: number,
  ): Promise<PresignedUploadUrlResponse> {
    const validatedInput = validateCreatePresignedUploadUrlBody({
      uploadPathPrefix,
      contentType,
    });

    if (
      !Number.isInteger(expiresInSeconds) ||
      expiresInSeconds < 1 ||
      expiresInSeconds > 3600
    ) {
      throw new BadRequestException(
        'expiresInSeconds must be an integer between 1 and 3600.',
      );
    }

    const extension = getUploadExtensionForContentType(
      validatedInput.contentType,
    );

    if (!extension) {
      throw new BadRequestException(
        'contentType must be a supported image MIME type.',
      );
    }

    const key = `${validatedInput.uploadPathPrefix}/${randomUUID()}.${extension}`;

    const command = new PutObjectCommand({
      Bucket: this.bucket,
      Key: key,
      ContentType: validatedInput.contentType,
    });
    const uploadUrl = await getSignedUrl(this.client, command, {
      expiresIn: expiresInSeconds,
    });

    return {
      key,
      expiresInSeconds,
      uploadUrl,
      publicUrl: this.publicBaseUrl
        ? `${this.publicBaseUrl.replace(/\/+$/, '')}/${key}`
        : null,
    };
  }

  /** A presigned PUT whose signature binds the content type and exact size. */
  async createPresignedPutUrlForKey(
    key: string,
    contentType: string,
    contentLength: number,
    expiresInSeconds = 300,
  ): Promise<string> {
    assertPrivateKey(key);

    return getSignedUrl(
      this.client,
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        ContentType: contentType,
        ContentLength: contentLength,
      }),
      { expiresIn: expiresInSeconds },
    );
  }

  /** A short-lived signed read for private media, shown only to its owner. */
  async createPresignedGetUrl(
    key: string,
    expiresInSeconds = 900,
  ): Promise<string> {
    assertPrivateKey(key);

    return getSignedUrl(
      this.client,
      new GetObjectCommand({ Bucket: this.bucket, Key: key }),
      { expiresIn: expiresInSeconds },
    );
  }

  /** A short-lived signed download that saves under the given file name. */
  async createPresignedDownloadUrl(
    key: string,
    fileName: string,
    expiresInSeconds = 300,
  ): Promise<string> {
    assertPrivateKey(key);

    return getSignedUrl(
      this.client,
      new GetObjectCommand({
        Bucket: this.bucket,
        Key: key,
        ResponseContentDisposition: `attachment; filename="${fileName.replace(/[^\w.-]/g, '-')}"`,
      }),
      { expiresIn: expiresInSeconds },
    );
  }

  async headObject(key: string): Promise<StoredObjectInfo | null> {
    assertPrivateKey(key);

    try {
      const result = await this.client.send(
        new HeadObjectCommand({ Bucket: this.bucket, Key: key }),
      );

      return {
        contentLength: result.ContentLength ?? 0,
        contentType: result.ContentType ?? null,
      };
    } catch (error) {
      const status = (error as { $metadata?: { httpStatusCode?: number } })
        .$metadata?.httpStatusCode;

      if (status === 404 || (error as { name?: string }).name === 'NotFound') {
        return null;
      }

      throw error;
    }
  }

  /** Stores a file the server produced (never a caller-chosen key). */
  async putObject(
    key: string,
    body: Buffer,
    contentType: string,
  ): Promise<void> {
    assertPrivateKey(key);

    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
      }),
    );
  }

  /** Streams a server-produced file into the private project namespace. */
  async putObjectFromFile(
    key: string,
    path: string,
    contentType: string,
  ): Promise<void> {
    assertPrivateKey(key);
    const { size } = await stat(path);

    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: createReadStream(path),
        ContentLength: size,
        ContentType: contentType,
      }),
    );
  }

  /** Streams a private object to a task-owned local file; false when missing. */
  async downloadObjectToFile(key: string, path: string): Promise<boolean> {
    assertPrivateKey(key);

    try {
      const result = await this.client.send(
        new GetObjectCommand({ Bucket: this.bucket, Key: key }),
      );

      if (!(result.Body instanceof Readable)) {
        throw new Error('S3 object body is not a readable stream.');
      }

      await pipeline(
        result.Body,
        createWriteStream(path, { flags: 'wx', mode: 0o600 }),
      );
      return true;
    } catch (error) {
      const status = (error as { $metadata?: { httpStatusCode?: number } })
        .$metadata?.httpStatusCode;
      if (
        status === 404 ||
        ['NoSuchKey', 'NotFound'].includes(
          (error as { name?: string }).name ?? '',
        )
      ) {
        return false;
      }
      throw error;
    }
  }

  /** Reads a stored file into memory; null when it no longer exists. */
  async getObjectBuffer(key: string): Promise<Buffer | null> {
    assertPrivateKey(key);

    try {
      const result = await this.client.send(
        new GetObjectCommand({ Bucket: this.bucket, Key: key }),
      );
      const bytes = await result.Body?.transformToByteArray();

      return bytes ? Buffer.from(bytes) : null;
    } catch (error) {
      if ((error as { name?: string }).name === 'NoSuchKey') return null;
      throw error;
    }
  }

  async deleteObject(key: string): Promise<void> {
    assertPrivateKey(key);

    await this.client.send(
      new DeleteObjectCommand({ Bucket: this.bucket, Key: key }),
    );
  }

  async copyObject(sourceKey: string, destinationKey: string): Promise<void> {
    assertPrivateKey(sourceKey);
    assertPrivateKey(destinationKey);

    await this.client.send(
      new CopyObjectCommand({
        Bucket: this.bucket,
        Key: destinationKey,
        CopySource: `${this.bucket}/${sourceKey}`,
      }),
    );
  }
}
